#!/usr/bin/env perl
use v5.30.0;
use warnings;

package Net::Async::UPnP;

my $SSDP_ADDR = '239.255.255.250';
my $SSDP_PORT = 1900;

my $DEFAULT_ST = q{upnp:rootdevice};
my $DEFAULT_MX = 1;

use IO::Async::Socket;

use IO::Async::Loop;
my $loop = IO::Async::Loop->new;

my $socket = IO::Async::Socket->new(
  on_recv => sub {
    my ($self, $dgram, $addr) = @_;

    print "Received reply: $dgram\n",
  },
  on_recv_error => sub {
    my ($self, $errno) = @_;
    die "Cannot recv - $errno\n";
  },
  on_send_error => sub { warn "yo" },
);

$loop->add( $socket );

$socket->connect(
  host     => $SSDP_ADDR,
  service  => 1900,
  socktype => 'dgram',
)->get;

my $ssdp_header = <<"END_REQUEST";
M-SEARCH * HTTP/1.1
Host: $SSDP_ADDR:$SSDP_PORT
Man: "ssdp:discover"
ST: $DEFAULT_ST
MX: $DEFAULT_MX
END_REQUEST

$ssdp_header =~ s/\r//g;
$ssdp_header =~ s/\n/\r\n/g;

$socket->send($ssdp_header);

$loop->run;
